#ifndef __CONFIG_H__
#define __CONFIG_H__

#define WIDTH_SCREEN 640
#define HEIGHT_SCREEN 480

#define BORDE_IZQUIERDO    1<<0
#define BORDE_SUPERIOR     1<<1
#define BORDE_DERECHO      1<<2
#define BORDE_INFERIOR     1<<3

#define FPS_LIMIT    30.0f
#define FPS_DELAY    1000.0f / FPS_LIMIT

#define SPRITE_MODULE_MI_NAVE 0

////SPRITES////
//////#TIPO_IMAGEN_NOMBRE//////
#define MODULO_MINAVE_NAVE						0
#define MODULO_MENUFONDO_FONDO					1
#define MODULO_ENEMIGO_NAVE						2
#define MODULO_MENUTEXTO_TITULO					3
#define MODULO_MENUTEXTO_NOMBRE					4
#define MODULO_MENUTEXTO_OPCION1				5
#define MODULO_MENUTEXTO_OPCION2				6
#define MODULO_MENUTEXTO_OPCION1SELECCIONADO    7
#define MODULO_MENUTEXTO_OPCION2SELECCIONADO    8
#define MODULO_BALAS_BALA                       9

#define MAXIMO_DE_BALAS          30

#define NAVE_PROPIA            0
#define NAVE_ENEMIGO           1

#endif